# Generated by Django 3.2 on 2022-12-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("movies", "0005_auto_20221206_0026"),
        ("movies", "0006_alter_personfilmwork_created"),
    ]

    dependencies = [
        ("movies", "0004_auto_20221203_2252"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="certificate",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="certificate"
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="person",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="person",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
