# Generated by Django 3.2 on 2022-12-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "movies",
            "0005_auto_20221206_0026_squashed_0006_alter_personfilmwork_created",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
